### ISSUE TITLE
Is it possible to get better tags in the Docker Hub?

### ISSUE THREAD

**Issue by x-cubed** [frol/docker-alpine-mono#4]
Currently, the Docker Hub lists only two tags for this image, latest and experimental: https://hub.docker.com/r/frolvlad/alpine-mono/

This makes it difficult to pin a particular version of the image, resulting in us pulling in Mono changes that we weren't expecting.

Can we get some more tags defined in the Docker Hub, ideally something based on the Mono version number, so that we can pin a particular Mono version?

**Comment by frol** [comment]
I will consider doing this. I think Arch Linux ARM (rollback machine) should work. Which versions are you interested in?

**Comment by x-cubed** [comment]
We're currently using an image with 4.4.0, but I see that the latest published image is 4.4.1.
It would be nice to have the future releases tagged.

**Comment by frol** [comment]
Hmm, does it change that much to have every minor release tagged?

**Comment by x-cubed** [comment]
Maybe not, but it makes builds more reproducible if they can be sure what version they're getting.

**Comment by nimaim** [comment]
@frol, not to revive an old issue but I am interested in this as well to get a reproducible build. If we keep pulling the latest, sooner or later builds that work today will likely break in the future. For example, I am using xbuild in this container on a VS solution file, and it's working flawlessly right now, but Mono claims xbuild is deprecated and will be removed from future releases. Since the build currently works, I don't want to worry about it and "baseline" it, but can't do that right now with the way your hub is set up. So as @x-cubed requested, is it possible to get some tags defined there (i.e. Mono v4.x.x, v5.x.x, etc.). I would at least like to see a tag with every major release of Mono.

**Comment by frol** [comment]
OK, I will make the tags. Is it OK if I only do 4.x (with the latest 4.8.0.495) and 5.x tags?

Arch Linux Archive has the following versions: https://archive.archlinux.org/packages/m/mono/

**Comment by nimaim** [comment]
@frol, sure, that works for me, hopefully @x-cubed as well. Something is better than nothing :) Generally Mono will only bump major version with API changes and major implementations of newer C# standards so keeping the latest major versions should be okay. Thank you by the way, your work on this is appreciated and makes our mono builds very easy.

**Comment by frol** [comment]
I have added 4.8-glibc, 5.0-glibc, and 5.4-glibc tags just in case someone needs the old glibc behavior and migrated the master (latest) to the testing mono package (my testing suite passed just fine on this testing package). https://github.com/frol/docker-alpine-mono/commit/4261a16d9a879f761466062cf8bbc0c3dde31c1e
