### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED using Microsoft.SharePoint.Client package

### ISSUE THREAD

**Issue by andreasseiler** [frol/docker-alpine-mono#7]
Hi there,

first thanks for providing this package! With the new version using the native Alpine Mono Package I get the following error when I try to connect to a Sharepoint instance using the Microsoft.SharePoint.Client package. For now I went back to the old version which works fine, but would be nice to use the new version :)

Thanks,
Andi

`Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED\n  at /home/buildozer/aports/testing/mono/src/mono-5.2.0.224/external/boringssl/ssl/handshake_client.c:1132)`

**Comment by frol** [comment]
Please, try installing `ca-certificates` and/or `openssl`:

```
apk add --no-cache ca-certificates
```


```
apk add --no-cache openssl
```

**Comment by andreasseiler** [comment]
Thanks for the quick response, I will try this!

**Comment by bvanreeven** [comment]
In order to get HTTPS to work with Mono, you have to import trusted root certificates into the Mono trust store. The following commands accomplish this. See http://www.mono-project.com/docs/faq/security/ for more information.

```
apk add --no-cache ca-certificates
cert-sync /etc/ssl/certs/ca-certificates.crt
```

I created a pull request that enables this by default for this image: https://github.com/frol/docker-alpine-mono/pull/8

**Comment by frol** [comment]
@bvanreeven Thank you!
